PP 30 Add a new class, render teacher's classes
Code-the-Dream-School/gg-pac-team4-front pull request #21
Opened 2024-08-26 16:29 UTC by vrudnitskaya

### Description
Implemented the addition of a new class to the teacher's dashboard. All teacher classes are now also displayed.
### Changes

### Related issues

### Screenshots
![filled-out-form](https://github.com/user-attachments/assets/9d876375-562c-4fa9-b517-de0fbfd85c5b)

After adding a class, the user is redirected to a page with all classes.
![added-class](https://github.com/user-attachments/assets/4b71a6de-cabb-4cef-8f71-2ec22e53338c)

There is validation of the form before it is sent to the server.
![form-errors](https://github.com/user-attachments/assets/3dcc20b0-cb84-494e-b97d-886a03eebe58)

If the form is submitted to the server and a validation error occurs, the error is also displayed.
![form-errors2](https://github.com/user-attachments/assets/06adbebe-05fa-4913-a6e9-7acbece25346)

2024-08-27 01:49 UTC, Tanyaa-a commented
Great work Valya! The add class form works great from my side!

2024-08-27 02:41 UTC, Tanyaa-a approved these changes

2024-08-27 02:41 UTC, Tanyaa-a commented on src/components/common/FormInput.jsx
The add new class works good from my side! Awesome work Valya!

2024-08-27 16:56 UTC, AnnaPestova1 requested changes
Hi Valya! Great job. Just a small issue, could we handle error message after we added category? 
<img width="673" alt="image" src="https://github.com/user-attachments/assets/6cfdd607-a509-4f72-b5da-510ba8a4eb1c">
here the full form after I added the info. I still have an error message in the category input 
<img width="1402" alt="image" src="https://github.com/user-attachments/assets/47fb4e1e-5dee-4180-be0c-b7ac1509c6dd">

and why we cannot add babies? 
<img width="654" alt="image" src="https://github.com/user-attachments/assets/036c15c6-6427-44b1-801b-cf75ff52418c">

2024-08-27 17:13 UTC, AnnaPestova1 commented on src/components/pages/dashboard-pages/AddClass.jsx
> +  const handleChange = (e) => {
Great function!

2024-08-28 04:26 UTC, vrudnitskaya commented
> 
> 
> Can you please take a look, do we need an error message if user does not have classes yet? (maybe we need something like: "add your first class" message instead? <img alt="image" width="1626" src="https://private-user-images.githubusercontent.com/106414157/361907998-971428a6-0811-4f13-9c0a-631297d20dc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTY2MjIsIm5iZiI6MTcyNDgxNjMyMiwicGF0aCI6Ii8xMDY0MTQxNTcvMzYxOTA3OTk4LTk3MTQyOGE2LTA4MTEtNGYxMy05YzBhLTYzMTI5N2QyMGRjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQwMzM4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDc2MDAzYjVhZTgwYmZmYjhiMzI1MmQ5NWZhYThmN2EyNmMzMDQ3NWYxYWRmODcyZTFjMDAwZTQ1MDliY2M1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PxGIjl2acZ6ehWUYtpfOTeinn4Y7KKu0p4ACSvhc6Rc">

fixed it
![no-classes-teacher](https://github.com/user-attachments/assets/a2446c5e-6545-4bdd-83fd-f4d0e674a4be)

2024-08-28 13:53 UTC, AnnaPestova1 approved these changes
Great work Valya! 

Please solve conflicts and check functionality before merging. 

I think we have a redundancy here, just take a look do we need both - the left and right sides to add the first class, or we can show the left part if classes exist?
<img width="1018" alt="image" src="https://github.com/user-attachments/assets/1baa0622-4fd2-4ed9-a153-2947c7733c12">

2024-08-28 17:10 UTC, vrudnitskaya commented
> Great work Valya!
> 
> Please solve conflicts and check functionality before merging.
> 
> I think we have a redundancy here, just take a look do we need both - the left and right sides to add the first class, or we can show the left part if classes exist? <img alt="image" width="1018" src="https://private-user-images.githubusercontent.com/106414157/362308594-1baa0622-4fd2-4ed9-a153-2947c7733c12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NjUzMDAsIm5iZiI6MTcyNDg2NTAwMCwicGF0aCI6Ii8xMDY0MTQxNTcvMzYyMzA4NTk0LTFiYWEwNjIyLTRmZDItNGVkOS1hMTUzLTI5NDdjNzczM2MxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQxNzEwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzA3M2VlYzZiNWI3NTNiMTQ1NjhjZGYyMTUzMzZhMGM3YzRlMzBhNmIyYzJjMzc2ZGU3NGE2NDUwZTE5ZjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.efhSOxN1DTUtwcSVV5Qmno-E5cRyFmEcLzx0CD1G628">

![no-classes](https://github.com/user-attachments/assets/2c35ba89-28b1-484e-8b31-23c1821f7cb5)

2024-08-28 17:10 UTC, merged