PP 68 fix date time in lessons
Code-the-Dream-School/gg-pac-team4-front pull request #51
Opened 2024-09-10 21:19 UTC by vrudnitskaya

### Description
I fixed the timer that wasn't working after adding the date formatting function. I also corrected the date formatting function itself.
### Changes

### Related issues

### Screenshots
![timer](https://github.com/user-attachments/assets/8643bc46-d0b3-4a60-9dd2-27fd5f6dc751)
![lessons-teacher](https://github.com/user-attachments/assets/2da4964d-0a93-4c0f-a4c0-f64f273dac5f)

2024-09-10 22:52 UTC, mariyador approved these changes
Thank you, Valya, for fixing that!

2024-09-11 03:43 UTC, ofeterovskaya approved these changes
Thank you Valya for catching this bug and fixing it

2024-09-11 14:49 UTC, AnnaPestova1 reviewed
Hi Valya!
Thank you for returning the functionality. 
Please, could you fix the time issue. Ny lesson is at 9 am tomorrow, it is 10.45 am right now. I see this notice:
<img width="585" alt="Your lesson starts in" src="https://github.com/user-attachments/assets/2d13751c-6bd8-4d4c-ade9-11b556356583">
(0d 25 hours).

2024-09-11 14:52 UTC, AnnaPestova1 commented on src/util/LessonsTimer.jsx
> +    ))+16;
I think adding hardcoded 16 can be an issue

2024-09-11 14:53 UTC, AnnaPestova1 requested changes
Hi Valya! 
Could you please check the comments and fix the bug.
Thank you

2024-09-11 15:38 UTC, AnnaPestova1 commented on src/util/LessonsTimer.jsx
> +      targetDate.toLocaleString('en-US', { timeZone: 'Asia/Tokyo' })
cool! seems you find location)

2024-09-11 15:39 UTC, AnnaPestova1 approved these changes
Valya! You did it! Congrats

2024-09-11 15:47 UTC, merged